# Generated by Django 2.2.6 on 2019-10-30 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registerapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='apkfile',
            field=models.FileField(blank=True, upload_to='apks/'),
        ),
        migrations.AlterField(
            model_name='app',
            name='image',
            field=models.FileField(blank=True, upload_to='images/'),
        ),
    ]
