# Generated by Django 2.2.6 on 2019-10-30 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registerapp', '0002_auto_20191030_0804'),
    ]

    operations = [
        migrations.RenameField(
            model_name='app',
            old_name='image',
            new_name='images',
        ),
    ]
