# Generated by Django 2.2.6 on 2019-10-31 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registerapp', '0004_auto_20191031_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='apkfile',
            field=models.FileField(blank=True, upload_to='images/'),
        ),
    ]
