# Generated by Django 2.2.6 on 2019-11-02 17:52

from django.db import migrations, models
import django_dropbox_storage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('registerapp', '0005_auto_20191031_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='apkfile',
            field=models.FileField(blank=True, storage=django_dropbox_storage.storage.DropboxStorage(), upload_to='images'),
        ),
        migrations.AlterField(
            model_name='app',
            name='images',
            field=models.FileField(blank=True, storage=django_dropbox_storage.storage.DropboxStorage(), upload_to='images'),
        ),
    ]
